import { GuestQuestClient } from "./guest-quest-client";
import { getDivisionsCatalog } from "@/app/actions/quest";
import { HeroMentrixerBounce } from "@/components/student/hero-mentrixer-bounce";
import { mentrixStudent } from "@/lib/mentrix-student-ui";
import { BackButton } from "@/components/ui/back-button";
import { ParticleTextEffect } from "@/components/ui/particle-text-effect";
import { Typewriter } from "@/components/ui/typewriter";
import { TiltCard } from "@/components/ui/tilt-card";

export default async function TryPage() {
  const divisions = await getDivisionsCatalog();
  const subjectOptions = divisions.map((d) => ({ key: d.key, name: d.name }));
  return (
    <div className={`${mentrixStudent.pageBg} relative min-h-screen overflow-hidden`}>
      <div className="pointer-events-none absolute inset-0 z-0 opacity-80">
        <HeroMentrixerBounce />
      </div>
      <div className={`${mentrixStudent.mainWide} relative z-10`}>
        <div className="mb-6">
          <BackButton />
        </div>
        <div className="mb-12 flex flex-col items-center text-center">
          
          <div className="mt-2 h-[48px] md:h-[64px] w-full flex justify-center">
            <ParticleTextEffect 
              words={["TRY A QUEST", "MENTRIXA", "PROVE IT", "CLIMB", "WIN"]} 
              className="text-center"
            />
          </div>
          <div className="mt-4 h-[24px] w-full flex justify-center">
            <Typewriter 
              text="Play five demo questions and see your score. No account required." 
              speed={40} 
              waitTime={5000} 
              className="text-center"
            />
          </div>
        </div>
        <div className="mt-8">
          {/* Client component handles the interactive flow */}
          <GuestQuestClient defaultSubjects={subjectOptions} />
        </div>
      </div>
      <div className="border-t border-slate-200/50 bg-white/30 backdrop-blur-sm py-10">
        <div className={mentrixStudent.mainWide}>
          <TiltCard tiltLimit={2} className="p-6 bg-white/40 border border-white/40 shadow-xl rounded-3xl backdrop-blur-md">
            <h2 className="text-lg font-bold text-slate-900 mb-4">Why try a Quest?</h2>
            <ul className="space-y-2.5 text-sm text-slate-700 max-w-2xl">
              <li className="flex gap-3">
                <span className="text-mentrixa-500 font-bold">✓</span>
                <span>Instant practice generated by Quest</span>
              </li>
              <li className="flex gap-3">
                <span className="text-mentrixa-500 font-bold">✓</span>
                <span>No account required to try the experience and see your score.</span>
              </li>
              <li className="flex gap-3">
                <span className="text-mentrixa-500 font-bold">✓</span>
                <span>Create your free account to save scores, earn real XP, and duel Mentrixers.</span>
              </li>
            </ul>
          </TiltCard>
        </div>
      </div>
    </div>
  );
}
