/**
 * Barrel re-export for email module.
 * All existing imports from `@/shared/integrations/email` continue to work unchanged.
 */

export { greetingFirstName } from "./shared";
export type { SessionEmailDetails } from "./shared";
export {
  baseTemplate,
  detailRow,
  ctaButton,
  secondaryLink,
  starRatingLinks,
  googleCalendarTemplateUrl,
  sessionFactsTable,
} from "./templates";
export {
  sendSessionBookedEmail,
  sendSessionConfirmedStudentEmail,
  sendSessionApprovedEmail,
  sendSessionConfirmedTutorEmail,
  type SessionReminderStudentEmailProps,
  sendSessionReminderStudentEmail,
  sendSessionReminderTutorEmail,
  sendSessionReminderEmail,
  type PreSessionBriefEmailData,
  sendPreSessionBriefEmail,
  sendAiPackageReadyEmail,
  sendSessionCompletedStudentEmail,
  type SessionCancelledByRole,
  type SessionCancelledStudentEmailProps,
  sendSessionCancelledStudentEmail,
  type RatingRequestEmailProps,
  sendRatingRequestEmail,
  type PaymentFailedEmailData,
  sendPaymentFailedEmail,
  type RefundIssuedEmailData,
  sendRefundIssuedEmail,
  type StudentCancelledEmailData,
  sendStudentCancelledEmail,
  type TutorCancelledEmailData,
  sendTutorCancelledEmail,
} from "./session";
export {
  type WelcomeStudentEmailProps,
  sendWelcomeStudentEmail,
  type WelcomeTutorEmailProps,
  sendWelcomeTutorEmail,
  sendWaitlistReceivedEmail,
  sendWaitlistDecisionEmail,
  type LevelUpEmailProps,
  sendLevelUpEmail,
  type DuelChallengeEmailProps,
  sendDuelChallengeEmail,
  type ReferralSuccessEmailProps,
  sendReferralSuccessEmail,
  type PasswordResetEmailProps,
  sendPasswordResetEmail,
  type TutorApprovedEmailProps,
  sendTutorApprovedEmail,
  type TutorPayoutEmailProps,
  sendTutorPayoutEmail,
  type VerificationStartedEmailData,
  sendVerificationStartedEmail,
  type VerificationApprovedEmailData,
  sendVerificationApprovedEmail,
  type VerificationRejectedEmailData,
  sendVerificationRejectedEmail,
  type VerificationBlacklistedEmailData,
  sendVerificationBlacklistedEmail,
  type VerificationInfoRequestEmailData,
  sendVerificationInfoRequestEmail,
  sendContactFeedbackInbound,
} from "./marketing";
